function opt = get_learners(rp)
opt = { 
    struct('method', 'mmhc', 'arity', 3, 'edge', false, ...
    'color', 'g-', 'discretize', false, 'normalize', true), ...
    
    struct('method', 'ksb', 'classifier', @kci_classifier, ...
    'kernel', GaussKernel(),  'arity', 1, 'nfunc', rp.nfunc, ...
    'prealloc', @kci_prealloc, 'pval', false, 'discretize', false, ...
    'edge', true, 'prune_max', rp.prune_max, 'color', 'm-', ...
    'normalize', true ), ...
    
    struct( 'method', 'ksb', 'classifier', @kci_classifier, ...
    'kernel', GaussKernel(),  'arity', 1, 'nfunc', rp.nfunc, ...
    'prealloc', @kci_prealloc, 'pval', true, 'discretize', false, ...
    'edge', true, 'prune_max', rp.prune_max, 'color', 'r-', ...
    'normalize', true), ...
    
    struct('method', 'bic','classifier', @sb_classifier, ...
    'params', struct('eta', 0.01, 'alpha', 1.0), 'normalize', true, ...
    'prealloc', @dummy_prealloc, 'arity', 4, 'discretize', true, ...
    'edge', false, 'color','b-')};

opt = opt(rp.f_sel);
end