function opt = get_learners(rp)
opt = { struct('method', 'mmhc', 'arity', 3, 'edge', false, ...
    'color', 'g-'), ...
    struct('method', 'sb3', 'classifier', @kci_classifier, ...
    'kernel', GaussKernel(),  'arity', 1, 'nfunc', rp.nfunc, ...
    'prealloc', @kci_prealloc, 'pval', false, ...
    'edge', true, 'prune_max', rp.prune_max, 'color', 'm-'), ...
    struct( 'method', 'sb3', 'classifier', @kci_classifier, ...
    'kernel', GaussKernel(),  'arity', 1, 'nfunc', rp.nfunc, ...
    'prealloc', @kci_prealloc, 'pval', true, ...
    'edge', true, 'prune_max', rp.prune_max, 'color', 'r-'), ...
    struct('method', 'bic','classifier', @sb_classifier, ...
    'params', struct('eta', 0.01, 'alpha', 1.0), ...
    'prealloc', @dummy_prealloc, 'arity', 4, ...
    'edge', false, 'color','b-')};
opt = opt(rp.f_sel);
end